"""
Extraction system for cleaned MS Celeb Dataset
"""
import base64
import os
from concurrent.futures import ThreadPoolExecutor
from os import path

import click
from tqdm import tqdm


def combine_label_files(first_file, second_file, output_file):
    """Given the paths of the clean_list_128Vec_WT051_P010 and
    relabel_list_128Vec_T058.txt, generate a 3rd file that is
    the combination of both. It simply appends one file on to the next.

    Args:
        first_file ([str]): path of clean list
        second_file ([str]): path of relabel listk
        output_file ([str]): path of output file 
    """

    file_names = [first_file, second_file]
    with open(output_file, 'w') as outfile:
        for fname in file_names:
            with open(fname) as infile:
                for line in infile:
                    outfile.write(line)


def read_last_n_lines(file_name, starting_byte):
    """Read the last N lines of a file. This function truncates the file
    after reading the bytes from starting_byte till the end of the file.

    Args:
        file_name ([string]): [path of the file to read]
        starting_byte ([int]): [number of bytes to jump to]

    Returns:
        A list of the lines read in the tsv
    """

    last_n_lines = []
    with open(file_name, "r+") as file:
        file_size = os.fstat(file.fileno()).st_size
        file.seek(0, os.SEEK_END)
        file.seek(file.tell() - min(starting_byte, file_size), os.SEEK_SET)
        file.readline()
        first_line_bytes = file.tell()

        counter = 0

        while True:
            line = file.readline()[:-1]  # remove the trailing endline
            if line:
                counter += 1
                last_n_lines.append(line.split("\t"))
            else:
                break

        file.seek(first_line_bytes)
        file.truncate()

        return [(line[0], line[1], line[4], line[-1]) for line in last_n_lines]


def construct_dictionary(combined_file_path):
    dictionary = {}

    with open(combined_file_path, "r") as f:
        lines = f.readlines()
        for line in lines:

            left, right = line.strip().split(" ")
            dictionary[right] = left

    return dictionary


# dic = construct_dictionary("./combined.txt")


# last_n_lines = read_last_n_lines(
#     "/home/harsh/Downloads/MS-Celeb-1M/data/aligned_face_images/FaceImageCroppedWithAlignment.tsv", 1000000, 100000000000)


# combine_label_files("./clean_list_128Vec_WT051_P010.txt",
# "relabel_list_128Vec_T058.txt", "./combined.txt")


def decode_and_save(dir_name, file_name, wrong_face_id, base64Image):
    """Take values from each line in the tsv and save it to 
    the directory with the name of the face id. 


    Args:
        dir_name (str): [path of the root directory to save to]
        file_name ([type]): [this is the first column's value in the tsv]
        wrong_face_id ([type]): [incorrectly labeled face id from the tsv]
        base64Image ([type]): [last column's value from the tsv]
    """
    key = f"{dir_name}/{file_name}-{wrong_face_id}.jpg"
    if key not in DIC:
        return

    class_name = DIC[key]
    full_path = path.join(OUTPUT_DIR, class_name)

    if not os.path.exists(full_path):
        os.makedirs(full_path)

    img_name = os.path.join(full_path, f"{file_name}.jpg")
    with open(img_name, 'wb') as f:
        imgdata = base64.b64decode(base64Image)
        f.write(imgdata)


TSV_LOCATION = None
OUTPUT_DIR = None
DIC = None


@click.group()
def group():
    """Utility to help extract MS Celeb data into manageable fils.
    """


@group.command()
@click.option("--tsv_location", type=click.Path(exists=True,dir_okay=False), help="Location of the entire MS Celeb tsv file", required=True)
@click.option("--output_dir", type=click.Path(), required=True, help="Output directory for images")
@click.option("--combined_file_path", type=click.Path(exists=True, dir_okay=False), required=True, help="Location of the file generated by combine command")
@click.option("--chunk_size", type=int, default=5000000, help="Number of bytes to read from the tsv at once")
@click.option("--num_threads", type=int, default=8)
def process(tsv_location, chunk_size, output_dir, combined_file_path, num_threads):
    """Read lines from the MS Celeb TSV file and save into a directory structure. 
    The files will be put in this format:

        root/person_x/xxx.jpg
        root/person_x/xxy.jpg
        root/person_x/xxz.jpg

        root/person_y/123.jpg
        root/person_y/817.jpg
        root/person_y/some.jpg

    !NOTE!: As this command reads the TSV, it will delete the lines already read.
    """
    global TSV_LOCATION
    global OUTPUT_DIR
    global DIC
    TSV_LOCATION = tsv_location
    OUTPUT_DIR = output_dir
    DIC = construct_dictionary(combined_file_path)
    with ThreadPoolExecutor(max_workers=num_threads) as executor:
        with tqdm() as pbar:
            while True:
                values = read_last_n_lines(
                    TSV_LOCATION, chunk_size)

                if not values:
                    break
                executor.map(decode_and_save, *list(zip(*values)))
                pbar.update()


@group.command()
@click.option("--clean_list_128_path", type=click.Path(dir_okay=False), help="Path of clean_list_128Vec_WT051_P010.txt", required=True)
@click.option("--relabel_list_128_path", type=click.Path(dir_okay=False), help="Path of relabel_list_128Vec_T058", required=True)
@click.option("--output_path", type=click.Path(dir_okay=False), help="Path of output file", required=True)
def combine(clean_list_128_path, relabel_list_128_path, output_path):
    """Combine clean_list_128Vec_WT051_P010.txt and relabel_list_128Vec_T058.txt together.

    The output of this file is used by the process command.
    """

    combine_label_files(clean_list_128_path,
                        relabel_list_128_path, output_path)


group()
